name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 根据仓库名自动推导 basePath：
      # - 如果仓库名是 <user>.github.io 则 basePath=""
      # - 否则 basePath="/<repo>"
      REPO_NAME: ${{ github.event.repository.name }}
      OWNER_NAME: ${{ github.repository_owner }}
      IS_USER_PAGES: ${{ endsWith(github.event.repository.name, '.github.io') && startsWith(github.event.repository.name, format('{0}.', github.repository_owner)) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            privacyvote-frontend/package-lock.json
            privacyvote-hardhat/package-lock.json

      - name: Compute basePath
        id: bp
        run: |
          REPO_NAME="${{ env.REPO_NAME }}"
          OWNER_NAME="${{ env.OWNER_NAME }}"
          if [[ "$REPO_NAME" == "$OWNER_NAME.github.io" ]]; then
            echo "base_path=" >> $GITHUB_OUTPUT
          else
            echo "base_path=/$REPO_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Install deps (frontend)
        working-directory: privacyvote-frontend
        run: npm ci --no-audit --no-fund

      - name: Build static site
        working-directory: privacyvote-frontend
        env:
          NEXT_PUBLIC_STATIC_EXPORT: "true"
          BASE_PATH: ${{ steps.bp.outputs.base_path }}
          NEXT_PUBLIC_BASE_PATH: ${{ steps.bp.outputs.base_path }}
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: privacyvote-frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

